<#
.SYNOPSIS
    Generate win/sources.cmake from src/Makefile.am.

.DESCRIPTION
    src/Makefile.am is the authoritative list of the sources that make up the
    SAC program and its in-tree libraries.  Rather than hand-copying ~1100
    file names into the CMake build (and letting the two drift apart), this
    script translates the automake variables into CMake lists.

    Only the sources that the WIN_APP configuration needs are emitted; the
    X11 (gd3.x11/) and macOS (osx/) back ends are dropped.

    Run from the repository root:   pwsh -File win/gen-sources.ps1
#>
[CmdletBinding()]
param(
    [string]$RepoRoot = ''
)

# Resolve the repository root at run time; $PSScriptRoot is not always
# populated (e.g. under `powershell -File`), so fall back to the script path
# and finally to the current directory.
if (-not $RepoRoot) {
    $scriptDir = $PSScriptRoot
    if (-not $scriptDir) { $scriptDir = Split-Path -Parent $MyInvocation.MyCommand.Path }
    if ($scriptDir) { $RepoRoot = Split-Path -Parent $scriptDir }
}
if (-not $RepoRoot) { $RepoRoot = (Get-Location).Path }

$makefileAm = Join-Path $RepoRoot 'src/Makefile.am'
$outFile    = Join-Path $RepoRoot 'win/sources.cmake'

if (-not (Test-Path $makefileAm)) {
    throw "cannot find $makefileAm (pass -RepoRoot)"
}

# automake variables -> CMake list names, for the WIN_APP configuration.
# Listed in link order.
$mapping = [ordered]@{
    'libsac_all_a'           = 'SAC_LIBSAC_ALL'
    'libsgf_a'               = 'SAC_LIBSGF'
    'libicm_a'               = 'SAC_LIBICM'
    'libmsg_a'               = 'SAC_LIBMSG'
    'libvars_a'              = 'SAC_LIBVARS'
    'libturtle_a'            = 'SAC_LIBTURTLE'
    'libsacio_a'             = 'SAC_LIBSACIO'
    'libSMnonOracleFuncs_a'  = 'SAC_LIBSMNONORACLE'
    'libSacOracleStubFuncs_a'= 'SAC_LIBSACORACLESTUB'
    'libsac_win_a'           = 'SAC_LIBSAC_WIN'
}

# Back ends that do not belong to a Windows build.
$excludeDirs = @('osx/', 'gd3.x11/')

$raw     = Get-Content -LiteralPath $makefileAm -Raw
$logical = $raw -replace "\\\r?\n", ' '

$vars = @{}
foreach ($line in ($logical -split "\r?\n")) {
    if ($line -match '^\s*([A-Za-z_][A-Za-z0-9_]*)_(SOURCES|LDADD)\s*\+?=\s*(.*)$') {
        $name = $Matches[1]
        $tokens = [regex]::Matches($Matches[3], '[A-Za-z0-9_./-]+\.(c|cpp|m|rc)\b') |
                  ForEach-Object { $_.Value }
        if ($tokens.Count) {
            if (-not $vars.ContainsKey($name)) { $vars[$name] = New-Object System.Collections.Generic.List[string] }
            foreach ($t in $tokens) {
                if (-not ($excludeDirs | Where-Object { $t.StartsWith($_) })) { $vars[$name].Add($t) }
            }
        }
    }
}

$sb = [System.Text.StringBuilder]::new()
[void]$sb.AppendLine('# Generated by win/gen-sources.ps1 -- do not edit by hand.')
[void]$sb.AppendLine('# Source of truth: src/Makefile.am')
[void]$sb.AppendLine('#')
[void]$sb.AppendLine('# These are the sources the WIN_APP configuration builds (the X11 and')
[void]$sb.AppendLine('# macOS back ends are excluded).  Re-run the generator after adding or')
[void]$sb.AppendLine('# removing files in src/Makefile.am.')
[void]$sb.AppendLine()

$total = 0
foreach ($amVar in $mapping.Keys) {
    if (-not $vars.ContainsKey($amVar)) {
        Write-Warning "src/Makefile.am has no ${amVar}_SOURCES"
        continue
    }
    $files = $vars[$amVar] | Select-Object -Unique
    $total += $files.Count
    [void]$sb.AppendLine("set($($mapping[$amVar])")
    foreach ($f in $files) { [void]$sb.AppendLine("    src/$f") }
    [void]$sb.AppendLine(')')
    [void]$sb.AppendLine()
}

# The sac executable itself: keep only the Windows entry point.
$sacMain = $vars['sac'] | Select-Object -Unique | Where-Object { $_ -like 'main/*' -or $_ -like 'win/*' }
[void]$sb.AppendLine('set(SAC_EXE_SOURCES')
foreach ($f in $sacMain) { [void]$sb.AppendLine("    src/$f") }
[void]$sb.AppendLine(')')
[void]$sb.AppendLine()

Set-Content -LiteralPath $outFile -Value $sb.ToString() -Encoding UTF8 -NoNewline

Write-Output "wrote $outFile"
Write-Output "sources: $total"
Write-Output 'SAC_EXE_SOURCES:'
$sacMain | ForEach-Object { Write-Output "  $_" }
foreach ($amVar in $mapping.Keys) {
    if ($vars.ContainsKey($amVar)) {
        Write-Output ("{0,-28} {1,5}" -f $mapping[$amVar], ($vars[$amVar] | Select-Object -Unique).Count)
    }
}
